node {
  echo 'Hello World from Jenkinsfile'
  echo ""
  echo "here are some global variables"
  echo "BRANCH_NAME = ${BRANCH_NAME}"
  echo "CHANGE_ID = ${CHANGE_ID}"
  echo "CHANGE_URL = ${CHANGE_URL}"
  echo "CHANGE_TITLE = ${CHANGE_TITLE}"
  echo "CHANGE_AUTHOR = ${CHANGE_AUTHOR}"
  echo "CHANGE_AUTHOR_DISPLAY_NAME = ${CHANGE_AUTHOR_DISPLAY_NAME}"
  if(env.CHANGE_AUTHOR_EMAIL) {
    echo "CHANGE_AUTHOR_EMAIL = ${CHANGE_AUTHOR_EMAIL}"
  }
  echo "CHANGE_TARGET = ${CHANGE_TARGET}"
  echo "BUILD_NUMBER = ${BUILD_NUMBER}"
  echo "BUILD_ID = ${BUILD_ID}"
  echo "BUILD_DISPLAY_NAME = ${BUILD_DISPLAY_NAME}"
  echo "JOB_NAME = ${JOB_NAME}"
  echo "JOB_BASE_NAME =${JOB_BASE_NAME}"
  echo "BUILD_TAG = ${BUILD_TAG}"
  echo "EXECUTOR_NUMBER = ${EXECUTOR_NUMBER}"
  echo "NODE_NAME = ${NODE_NAME}"
  echo "NODE_LABELS = ${NODE_LABELS}"
  echo "WORKSPACE = ${WORKSPACE}"
  echo "JENKINS_HOME = ${JENKINS_HOME}"
  echo "JENKINS_URL = ${JENKINS_URL}"
  echo "BUILD_URL = ${BUILD_URL}"
  echo "JOB_URL = ${JOB_URL}"
  echo ""
}
